# Generated by Django 5.1.6 on 2025-02-22 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_category_product_category_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام شخص/سازمان')),
                ('customer_type', models.CharField(choices=[('i', 'شخص'), ('company', 'شرکت/سازمان')], default='i', max_length=20, verbose_name='نوع مشتری')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('address', models.TextField(verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='image size must be 1024*614 pixel', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_images', to='web.product'),
        ),
    ]
