# Generated by Django 5.1.6 on 2025-02-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(help_text='image size must be 142 * 41', null=True, upload_to='images/customer'),
        ),
    ]
