# Generated by Django 5.1.6 on 2025-04-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='blog',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس کاور'),
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default='No description', verbose_name='شرح'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیرفعال'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.TextField(verbose_name='خلاصه'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
    ]
